Remove clutter

diff --git a/git-reflow b/git-reflow
--- a/git-reflow
+++ b/git-reflow
@@ -1,27 +1,13 @@
 #!/bin/bash
 
-# ANSI color codes
-RED='\033[0;31m'
-GREEN='\033[0;32m'
-YELLOW='\033[1;33m'
-BLUE='\033[0;34m'
-NC='\033[0m' # No Color
-
-# Welcome Message
-echo -e "${GREEN}Welcome to Git Reflow!${NC}"
-echo -e "${BLUE}Let's create a new branch from the 'develop' branch.${NC}"
-
-# Ensure the user is on the develop branch and it's up to date
 git checkout develop
 git pull
-echo -e "${YELLOW}Switched to 'develop' and updated.${NC}"
 
-# Get branch type and description from the user
-echo -e "${YELLOW}Select the type of branch you want to create:${NC}"
-echo -e "1) ${GREEN}feature${NC}"
-echo -e "2) ${GREEN}fix${NC}"
-echo -e "3) ${GREEN}hotfix${NC}"
-echo -e "4) ${GREEN}enhancement${NC}"
+echo -e "${YELLOW}Select the type of branch you want to create:"
+echo -e "1) feature"
+echo -e "2) fix"
+echo -e "3) hotfix"
+echo -e "4) enhancement"
 read -p "Enter your choice (1-4): " choice
 
 case $choice in
@@ -30,12 +16,10 @@ case $choice in
     3) branch_type="hotfix";;
     4) branch  extension="enhancement";;
     5) branch_type="docs";;
-    *) echo -e "${RED}Invalid choice${NC}"; exit 1;;
+    *) echo -e "Invalid choice"; exit 1;;
 esac
 
 read -p "Enter the branch description: " description
 branch_name="${branch_type}/$(echo $description | tr ' ' '-')"
 
-# Create the branch
 git checkout -b $branch_name
-echo -e "${GREEN}Branch created and checked out: ${branch_name}${NC}"
